### ISSUE TITLE
Runs on only 2 devices + reports folder name

### ISSUE THREAD

**Issue by pr4bh4sh** [saikrishna321/PageObjectPatternAppium#1]
Hi @saikrishna321 
I'm trying to integrate your repo with my setup. However while running the this code base as is on my system i found these things
1. Test runs on only 2 device:- I have 2 emulators and 1 real device and the test only run on two of the device, ie. on both emulator or one emulator and on real device.
2. The report folder structure has variable as folder name
![image](https://cloud.githubusercontent.com/assets/6311526/12141353/b49fe644-b494-11e5-9d36-811398215867.png)

**Comment by pr4bh4sh** [comment]
Excerpt of the log where it starts the execution.
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.appium.tests.Runner
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@2a098129
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
creating directory: Logs
DIR created
creating directory: ADBLogs
DIR created
adb service already started
Following device is connected
4d006f0995e83041 samsung GT-I9500 5.0.1

Following device is connected
emulator-5556 generic_x86 AndroidSDKbuiltforx86 4.4.4

Following device is connected
emulator-5554 generic_x86 AndroidSDKbuiltforx86 4.4.4

Total Number of devices detected::3
starting running tests in threads
forEach: true
forEach: true
Running test file: com.appium.tests.WritePostTest
Into TestNGRunner
Running test file: com.appium.tests.WritePostTest2
Into TestNGRunner
[TestNG] Running:
  Command line suite

[TestNG] Running:
  Command line suite

adb service already started
adb service already started
*************pool-1-thread-1
******Current Thread Running*******1
Starting Appium Server
4d006f0995e83041
*************pool-1-thread-2
******Current Thread Running*******2
Starting Appium Server
emulator-5556
info: Welcome to Appium v1.3.5 (REV a124a15677e26b33db16e81c4b3b34d9c6b8cac9)
info: Welcome to Appium v1.3.5 (REV a124a15677e26b33db16e81c4b3b34d9c6b8cac9)
info: Appium REST http interface listener started on 0.0.0.0:57750
info: Appium REST http interface listener started on 0.0.0.0:57749
info: Console LogLevel: info
info: File LogLevel: info
info: Console LogLevel: info
info: File LogLevel: info
```

**Comment by saikrishna321** [comment]
@pr4bh4sh hey thanks for giving it a try .


Can you please take a pull and try out.. I actually had only 2 tests and you have 3 devices.. 

Now i have added an other test, try that out ..  You must open ExtentReports.html

**Comment by pr4bh4sh** [comment]
Oh, I thought you are running the thread based on the number of device connected, rather than the no of tests you have.
I tried with latest version and it's working now.
And yes ExtentReport is awesome, I've been using it quite some times.
:+1:

**Comment by saikrishna321** [comment]
@pr4bh4sh thats kool .. if u set the RUNNER to parallel then its gonna to run all your tests on each device. 

It would be help-full if u can write some more tests and a pull-request

**Comment by saikrishna321** [comment]
@pr4bh4sh  take a look at this, i have more updates to this .. 

https://github.com/saikrishna321/AppiumTestDistribution

Have support for selendroid mode and web parallel as well..

**Comment by pr4bh4sh** [comment]
Yes i came here from that repo.
And yes I'll try contributing directly via code.(Just moved from SVN ,GIT is very new to me)

**Comment by saikrishna321** [comment]
@pr4bh4sh thanks :+1:
