### ISSUE TITLE
Question: How to implement add MobileElement a description annotation

### ISSUE THREAD

**Issue by ansonliao** [saikrishna321/PageObjectPatternAppium#14]
Hi @saikrishna321 
I would like to make extentreport more detail in test step/operation.

I created a annotation name `@ElementDescription` for `MobileElement`, and in `page` class, log the mobile element's description to extentreport.

for example, for this repository project `PageObjectPatternAppium`, the page class `LoginPage.java`, and page object `LoginPageObjects.java`:

Add `@ElementDescription` to MobileElement `sign_in`:

```java
public class LoginPageObjects {
    ...
    @AndroidFindBy(xpath = ".//*[@text='Sign in']") 
    @iOSFindBy(id = "Sign In")
    @ElementDescription("Login Page: SignIn Button")
    public MobileElement sign_in;
    ...
}
```

In `com.appium.pages.LoginPage.java`, define a method named `clickSignInBtn()`, and add extentreport log function into it, so that more easier to trace the test step/operation and more easier to debug the failure by non-programming skill tester:

```java
public class LoginPage extends CommonAppiumTest {
    ...
    public LoginPageObjects loginPageObjects = new LoginPageObjects();

    public LoginPage(AppiumDriver<MobileElement> driver) {
        ....
    }

    ....

    public void clickSignInBtn() {
        // how to retrieve mobile element reference loginPageObjects.sign_in description here
        String elementDescription = null;     // How_To_Get_Sign_in_MobileElement_Description

        // Log test step/test operation by extentreport instance
        ExtentTestManager.getTest().log(LogStatus.INFO, "Click: " + elementDescription);
        loginPageObjects.sign_in.click()
    }
}
```

could you advise that how I can retrieve  loginPageObjects.sign_in 's description in method `clickSignInBtn()`?

**Comment by saikrishna321** [comment]
@ansonliao can you please share the code snippet for @MobileDescription, will surely take a look.. This looks like a kool feature and should be part of the AppiumTestDistribution

**Comment by ansonliao** [comment]
@saikrishna321 
Actually, the code to define `@MobileDescription` is very simple, please check below:

```java
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface MobileDescription {
    String value() default "";
}
```

In my further idea, should have another annotation for Page named `@PageName`, so that look like this:

```java
@PageName("Login Page")
public class LoginPage extends CommonAppiumTest {
    ....
}
```

`@MobileDescription ` should be used like below, remove page description will be more simple:

```java
public class LoginPageObjects {
    ...
    @AndroidFindBy(xpath = ".//*[@text='Sign in']") 
    @iOSFindBy(id = "Sign In")
    @ElementDescription("SignIn Button")
    public MobileElement sign_in;
    ...
}
````

after retrieve `@PageName` and `@ElementDescription`, the completed mobile element's description should be combined with page name, like this: `Login Page: SignIn Button`

Also, I custom a `Click` method in `CommonAppiumTest.java`, the code snippet look like this:

```java
public void click(MobileElement mobileElement) {
    // retrieve mobileElement's completed description here
    String elementDescription = null; 

    // Log to extentreport
     ExtentTestManager.getTest().log(
                LogStatus.INFO, elementDescription);
    mobileElement.click();
}
```

**Comment by ansonliao** [comment]
@saikrishna321 
I tried to extend `MobileElement` for add a new attribute named `elementDescription` in String, but fail.

```java
public class ExtendMobileElement extends MobileElement {

    private String elementDescription;

    public String getElementDescription() {
        return elementDescription;
    }

    public void setElementDescription(String elementDescription) {
        this.elementDescription = elementDescription;
    }
}
```

**Comment by saikrishna321** [comment]
@ansonliao this looks awesome.. will you able to push these changes to your repo i can fork and take a look .. this is good to have feature 👍

**Comment by ansonliao** [comment]
@saikrishna321 
thanks for your reply.
I will let you know the repo after I push.

**Comment by ansonliao** [comment]
@saikrishna321 
I push the code to my repo, please check it via the link below.
https://github.com/ansonliao/PageObjectPatternAppium

please run the project in TestNG framework by command:

```bash
mvn clean test -Dtest=Runner
```

1. Please note on package `com.example.custom`, I created some annotations on this package: `@ElementDescription`, `@PageName`, `@Author`, `@Description` of test class.

2. I added annotation `@ElementDescription` to MobileElement variable `sign_in` of `LoginPageObjects.java`.

3. Added ExtentReport log step in `CommonAppiumTest.java`, for example, `SwiftLeft()`, `click()`, `type()`, etc..

4. Custom demonstration test case for logging test step/operation into extentreport: `DemoTest.java`, please don't care the test cases correct or not, it is just a demonstration.

5. `@ElementDescription` not relative to Extentreport log now, as this issue mention, I no idea how to retrieve it in Extentreport log calling in CommonAppiumAction.java, etc..


![image](https://cloud.githubusercontent.com/assets/6060224/17457450/482c20ec-5c2b-11e6-88d8-86440037414e.png)

**Comment by ansonliao** [comment]
@saikrishna321 

Please note on package com.example.custom, the classes `CustomAppiumParallelTest.java`, `CustomMyTestExecutor.java`, `CustomParallelThread.java`.

In my project, I never use `AppiumTestDistribution.jar` classes `AppiumParallelTest.java`, `MyTestExecutor.java`, `ParallelThread.java`, the reason is I need to attach JENKINS URI in test of Appium, log of ADB, failure screenshot in JENKINS, so that those links are valid in JENKINS.

so I created a new property `JENKINS_BASE_URI` to `config.properties`, and replaced extentreport log function, replaced the logs link starting `System.getProperty("user.dir")` with `JENKINS_BASE_URI` if property `JENKINS_BASE_URI` was filled, otherwise will use `System.getProperty("user.dir")`.

we are discussing this issue in the link: 
https://github.com/saikrishna321/AppiumTestDistribution/issues/82

for example:

Snipping of CustomAppiumParallelTest.java

```java
...
private static String JENKINS_BASE_URI = null;
...

static {
    ...
    if (prop.containsKey("JENKINS_BASE_URI")) {
                JENKINS_BASE_URI =
                        prop.getProperty("JENKINS_BASE_URI").toString().trim();
            }

            if (JENKINS_BASE_URI == null || JENKINS_BASE_URI.isEmpty()) {
                JENKINS_BASE_URI = System.getProperty("user.dir");
            }
    ...
}
```

```java
public synchronized AppiumServiceBuilder startAppiumServer(String methodName) throws Exception {
    ...
    if(prop.getProperty("FRAMEWORK").equalsIgnoreCase("testng")) {
        ...

        ExtentTestManager.getTest().log(
                        LogStatus.INFO,
                        "AppiumServerLogs",
                        "<a href=" + JENKINS_BASE_URI + "/target/appiumlogs/" + this.device_udid.replaceAll("\\W", "_") + "__" + methodName + ".txt" + ">Logs</a>");
    
        ...
    }
    ...
}
```

**Comment by saikrishna321** [comment]
@ansonliao thanks for the code snippet will take a look and i will try merging it within the repo.. 

@akhilbojedla did mention that he has started to work on the JENKINS_BASE_URI path in the report .. 

@akhilbojedla any updates?

**Comment by saikrishna321** [comment]
@ansonliao i have a solution for 

> @ElementDescription not relative to Extentreport log now, as this issue mention, I no idea how to retrieve it in Extentreport log calling in CommonAppiumAction.java, etc.

i'm merging this with master, need a day for it.... So now if the user adds @ElementDescription for any MobileElement then it will log to the report, you don't have to add any more changes to the CommonClass..

And i still don't see the use of Description and Author as there is no logging happening. You have it on purpose?

**Comment by ansonliao** [comment]
@saikrishna321,
I added @Author to test case method, please check test case method of DemoTest.java, also I added assigned test case scripting' s author in extent report in UserBaseTest.java, but it seem that after author assigned in extentreport, can't found author information in extentreport the test generated.  

Also for @Description, my purpose is add test description for test class, for example, "LoginPageTest.java", description "Login page functionality test", please also check test class "DemoTest.java", I added class annotation @Description "Demonstration", add retrieve in UserBaseTest.java.  

https://github.com/NetEase/arrow/blob/master/README.md

**Comment by saikrishna321** [comment]
@ansonliao check the screens below. You can filter the test with Author now. Does this look good??

<img width="1437" alt="screen shot 2016-08-09 at 1 09 59 pm" src="https://cloud.githubusercontent.com/assets/4045041/17508395/657795b0-5e32-11e6-8fff-d5216f10f825.png">
<img width="1007" alt="screen shot 2016-08-09 at 1 10 08 pm" src="https://cloud.githubusercontent.com/assets/4045041/17508402/6c0679e6-5e32-11e6-8cb4-8ca3a9422668.png">

**Comment by ansonliao** [comment]
@saikrishna321 
Hi Saik, do you add author as "Group" of extentreport?

it is no problem to me, thanks for your great work on it.


Actually, why I added author because more QA will join appium scripting in my company (I am automation team, not QA team), and we are expect that when we are review the extentreport can very easy to identify the script's author, and the let the author to check wether includes code improve issue.
this is just the requirement of my.

I remember that extentreport, have a filter and display content to author as tag, but now I can't find, maybe extentreport updated.

**Comment by saikrishna321** [comment]
@ansonliao i have added it under the category, so that u can filter the tests as in which author it belongs to.

What is going wrong when u add the JENKINS_URL to screenshot? I see in the screenshot u attached the image is not loaded

**Comment by ansonliao** [comment]
@saikrishna321 

For JENKINS_URL, my screenshot just a demonstration, as I completed the code in home, last weekend (my home's Mac, no local Jenkins set).

**Comment by saikrishna321** [comment]
Will u able to see PR for Jenkins URL ?

**Comment by ansonliao** [comment]
@saikrishna321 
sorry, what it is "PR"?

**Comment by saikrishna321** [comment]
@ansonliao pull request :)

**Comment by ansonliao** [comment]
@saikrishna321 
below is my adb log in Jenkins for review.
in this example, 
the completed adblog url is "http://192.168.3.100/job/wispi-android-appium-ui-tests/ws/target/appiumlogs/110e96bc__DebugTest.txt"

the JENKINS_BASE_URI should be "http://192.168.3.100/job/wispi-android-appium-ui-tests/ws", because this link is appium test project root directory in Jenkins workspace.



![image](https://cloud.githubusercontent.com/assets/6060224/17513776/7bca9bb2-5e61-11e6-8296-67e84ea86000.png)

**Comment by ansonliao** [comment]
@saikrishna321 
what is the PR of Jenkins URL?
you means that, check the appium test project source code from VC system by Jenkins?

**Comment by saikrishna321** [comment]
@ansonliao no 

> In my project, I never use AppiumTestDistribution.jar classes AppiumParallelTest.java, MyTestExecutor.java, ParallelThread.java, the reason is I need to attach JENKINS URI in test of Appium, log of ADB, failure screenshot in JENKINS, so that those links are valid in JENKINS.

If this is the reason for you not to use the AppiumTestDistribution dependency then why don't you send a pull request with the changes you have done for JENKINS_URL_PATH in you fork.

**Comment by ansonliao** [comment]
@saikrishna321 
I used AppiumTestDistribution dependency in my appium parallel project, but I am not use those three classes AppiumParallelTest.java, MyTestExecutor.java, ParallelThread.java of AppiumTestDistribution dependency.

**Comment by saikrishna321** [comment]
Any reason for not using those classes ?

**Comment by ansonliao** [comment]
@saikrishna321 
As described I raised up: https://github.com/saikrishna321/AppiumTestDistribution/issues/82

As I need to present `test log txt` and `screenshot` in Jenkins, so I found that, log `test log txt` and `screenshot` in ExtentReport, the code is in class [AppiumParallelTest.java](https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/manager/AppiumParallelTest.java), I tried to extends this class, and `proxy` this class, and found that

1. If extends to `AppiumParallelTest.java`, some private variables in `AppiumParallelTest.java` can't not use in `BaseTest.java`.

2. If `proxy` into `AppiumParallelTest.java`, will be recorded twice or record failure screenshot with `System.getProperty("user.dir")` first and then record the my change.

so finally, I use a stupid way, rename `AppiumParallelTest.java` to `CustomAppiumParallelTest.java` in my test project (create a new class, and named it), and then updated the test log text and screenshot code of ExtentReport in to my Jenkins basic URL.

and then I extends my `BaseTest.java` to `CustomAppiumParallelTest.java` in my test project, and now, I found a problem.

the problem is in [ParallelThread.java](https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/manager/ParallelThread.java), have a statement 

```java 
   MyTestExecutor myTestExecutor = new MyTestExecutor();
```

so if I want to use my customise class `CustomAppiumParallelTest.java`, I also need to change this to:

```java
   CustomMyTestExecutor myTestExecutor = new CustomMyTestExecutor();
```

and then I also found a problem, it is in [MyTestExecutor.java](https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/executor/MyTestExecutor.java), for `TestNG` platform, have add `AppiumParallelTest.java` as listener 

```java
listeners.add("com.appium.manager.AppiumParallelTest");
```

so in this class, I also need to add my customise `CustomAppiumParallelTest.java` as listener.

so I created those three customise classes for my Jenkins URL support.


BTW, as we are introducing cucumber in Appium, so if no Jenkins URL support in AppiumTestDistribution dependency, I will also need to add a customise for [ExtentCucumberFormatter.java](https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/cucumber/listener/ExtentCucumberFormatter.java) to `CustomExtentCucumberFormatter` for support my Jenkins URL in cucumber test case.

**Comment by ansonliao** [comment]
@saikrishna321 
I also hope that have others good solution to support my Jenkins URL case, as I created those three classes, I can't keep my AppiumTestDistribution dependency update, as I used the latest AppiumTestDistribution dependency before, I have to check those three classes AppiumParallelTest.java, MyTestExecutor.java, ParallelThread.java whether have the code updated, so that my three customise classes also keep update.

please advise.

**Comment by saikrishna321** [comment]
Okays.... keeping it simple, you have pulled these classes because of JENKINS remote URL config ... if yes, then I can work on it ... so that you can always have the master code...

**Comment by ansonliao** [comment]
@saikrishna321 
As I hope that AppiumTestDistribution dependency will support this CI system URL feature, because maybe others user of AppiumTestDistribution have other CI system to run the test project.

Also, I think Appium is a automation test tool for mobile, and it is very great that @saikrishna321 you are distribute a parallel mode in real device in Appium, so as a automation test tool, run test project with AppiumTestDistribution framework locally is not "Automation", it is half manually test, and half automation test tool.

**Comment by saikrishna321** [comment]
@ansonliao i will fix this as well part if this push

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/issues/82 

i have made all the changes required, try to execute from master n see if things work as expected

**Comment by ansonliao** [comment]
@saikrishna321 
thanks for your work, as vacation days, I will check the latest version of AppiumTestDistribution soon.

**Comment by saikrishna321** [comment]
@ansonliao sample test to log description and PageName 

https://github.com/saikrishna321/PageObjectPatternAppium/blob/df85093d9adaaeb459268015269b544ba30b0772/src/test/java/com/appium/pages/LoginPage.java#L41

**Comment by ansonliao** [comment]
@saikrishna321 
apology for late validation on the CI_BASE_URL added in `config.properties`, it works.
by the way, I saw Extentreport's author replied, extentreport will be support related path of the screenshot or text, so CI_BASE_URL will be removed from `config.properties`, right?

I would like to know, AppiumTestDistribution, when will be updated to support related path version of extentreport?

thanks for your great work.

**Comment by ansonliao** [comment]
@saikrishna321 
thanks for your work on mobile element description.

I would like to know, for your solution, can add the logging step of extentreport in the class `CommonAppiumTest.java`?

for example, the snip of `CommonAppiumTest .java`:

```java
public void sendKeys(MobileElement mobileElement, String typeStr) {
    logStepIntoExtentReport(getPageObjectElemetDescription(mobileElement), "SendKeys", typeStr);

    mobileElement.sendKeys(typeStr);
}

public void click(MobileElement mobileElement) {
    logStepIntoExtentReport(getPageObjectElemetDescription(mobileElement), "Click", "Click: " + getPageObjectElemetDescription(mobileElement);
}
```

for current solution, looks like is not common.

**Comment by saikrishna321** [comment]
@ansonliao 
 

> when will be updated to support related path version of extentreport?
Once extentreport has v3 release, currently they are beta

you above solution looks good.. Will make changes ..

**Comment by ansonliao** [comment]
@saikrishna321 
Hope can hear good news from you soon.

by the way, for `PageObjectPatternAppium` project, the cucumber test always run in fail, could you advise which commit is works in cucumber framework?

**Comment by shaynl** [comment]
@ansonliao
This is a good improvement that I'm now try to implement in my code and looking for a simple way to get the ElemetDescription. Can you please share the function getPageObjectElemetDescription(mobileElement)?

**Comment by ansonliao** [comment]
@shaynl 
I no `getPageObjectElemetDescription(mobileElement)` method's implementation, you can discuss with @saikrishna321 for more details, and this method provided by him.

**Comment by saikrishna321** [comment]
@shaynl you can find the method here 
https://github.com/saikrishna321/PageObjectPatternAppium/blob/df85093d9adaaeb459268015269b544ba30b0772/src/test/java/com/appium/config/CommonAppiumTest.java#L121

**Comment by shaynl** [comment]
@saikrishna321 
Is there a simple way to get just ElemetDescription (without PageName) directly from the mobileElement?
