### ISSUE TITLE
How can I run mobile web app test parallel using this framework?

### ISSUE THREAD

**Issue by gaurabhi1986** [saikrishna321/PageObjectPatternAppium#16]
Hi,

I need to execute my mobile web app test on multiple devices.

Can you please help me for below queries: 
- How can I use this framework to execute my mobile web test parallel ?
- How can I run my test on remotely hosted devices ?

Thanks,
Abhishek Gaur

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/issues/122
