### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by prathimak** [saikrishna321/PageObjectPatternAppium#28]
Hi,

I have downloaded the framework and trying to run tests on windows machine using below commands

To Run the TestNG test

* mvn clean -Dtest=Runner test
To Run the Cucumber test

* mvn clean -Dtest=RunnerCukes test

got below error

[ERROR] Plugin com.github.saikrishna321:cucumber-jvm-parallel-plugin:2.0.9 or on
e of its dependencies could not be resolved: Failed to read artifact descriptor
for com.github.saikrishna321:cucumber-jvm-parallel-plugin:jar:2.0.9: Could not t
ransfer artifact com.github.saikrishna321:cucumber-jvm-parallel-plugin:pom:2.0.9
 from/to jitpack.io (https://jitpack.io): Not authorized by proxy , ReasonPhrase
:Proxy Authentication Required. -> [Help 1]

**Comment by saikrishna321** [comment]
@prathimak make sure your not behind any proxy

**Comment by prathimak** [comment]
ok i tried now but unable to find APPIUM_JS_PATH on windows

**Comment by Rajazpandi** [comment]
there are more than one main.js file which one should i use

**Comment by hemano** [comment]
@saikrishna321 I'm also facing the same problem. From where do I get the APPIUM_JS_PATH on windows?

**Comment by saikrishna321** [comment]
inside the node_modules you should see appium

**Comment by hemano** [comment]
Thanks, below path works for me.
C:/Users/<username>/AppData/Roaming/npm/node_modules/appium/build/lib/main.js
