### ISSUE TITLE
I got UnsupportedClassVersionError

### ISSUE THREAD

**Issue by rajamobiletech** [saikrishna321/PageObjectPatternAppium#3]
Hi,

When run my test case on my machine it throwing error like this,

T E S T S
-------------------------------------------------------
Running com.appium.tests.Runner
Configuring TestNG with: TestNG652Configurator
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.39 sec <<< FAILURE!
testRunner(com.appium.tests.Runner)  Time elapsed: 0.013 sec  <<< FAILURE!
java.lang.UnsupportedClassVersionError: com/appium/manager/ParallelThread : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.appium.tests.Runner.testRunner(Runner.java:11)

Can you please help me to fix this issue ?

**Comment by saikrishna321** [comment]
Please make sure u have Java 1.8

**Comment by rajamobiletech** [comment]
ya.. i'm using java 1.8

**Comment by rajamobiletech** [comment]
I fixed this issue.. Issue with my java8. Thanks for your quick reply sai.

When i run my test case i got like this.

------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.appium.tests.Runner
Configuring TestNG with: TestNG652Configurator
creating directory: Logs
creating directory: ADBLogs
Android 192.168.56.101:5555 Directory is created!
Android 192.168.56.102:5555 Directory is created!
Android 192.168.56.103:5555 Directory is created!
Total Number of devices detected::3
starting running tests in threads
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.663 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------


But apk file is not installing on my genymotion simulator.
I mean say automation is not running on my device/simulator.
Do you have any idea to fix this issue?

**Comment by saikrishna321** [comment]
How r u running the project ? If command line pls give the command ?

**Comment by rajamobiletech** [comment]
mvn clean -Dtest=Runner test

just i'm running this command

**Comment by saikrishna321** [comment]
Can u pls paste your config.properties ? Just wanted to make sure u have the right Appium js path n other properties set ...

**Comment by rajamobiletech** [comment]
This is my config.properties.

ANDROID_APP_PATH=/Users/rajaduraisamy/Desktop/PageObjectPatternAppium-master/build/wordpress.apk
APP_PACKAGE=org.wordpress.android
APP_ACTIVITY=org.wordpress.android.ui.WPLaunchActivity
RUNNER=distribute
APPIUM_JS_PATH=/Users/rajaduraisamy/appium-master/libmain.js
BROWSER_TYPE=chrome
APP_TYPE=NA
FRAMEWORK=cucumber

**Comment by rajamobiletech** [comment]
This is my config.properties file.

ANDROID_APP_PATH=/Users/rajaduraisamy/Desktop/PageObjectPatternAppium-master/build/wordpress.apk
APP_PACKAGE=org.wordpress.android
APP_ACTIVITY=org.wordpress.android.ui.WPLaunchActivity
RUNNER=distribute
APPIUM_JS_PATH=/Users/rajaduraisamy/appium-master/lib/main.js
BROWSER_TYPE=chrome
APP_TYPE=NA
FRAMEWORK=cucumber

**Comment by saikrishna321** [comment]
@rajamobiletech please change the FRAMEWORK=testng and give it a try .. 

As you have closed the issue i'm assuming the issue is fixed
