### ISSUE TITLE
Plugin execution not covered by lifecycle configuration: com.github.saikrishna321:cucumber-jvm-parallel-plugin:2.0.9:generateRunners (execution: generateRunners, phase: generate-test-  sources)

### ISSUE THREAD

**Issue by benz-philip** [saikrishna321/PageObjectPatternAppium#33]
May I know how to resolve the below issue?

![screen shot 2017-05-11 at 5 03 29 pm](https://cloud.githubusercontent.com/assets/18724283/25950601/86a5ed14-366c-11e7-9907-b6d789ac8cd8.png)

**Comment by saikrishna321** [comment]
this eclipse issue ... use intellji

**Comment by benz-philip** [comment]
Sure Sai. Thank you very much for your support!

**Comment by benz-philip** [comment]
I ignored the error and its working fine now
