### ISSUE TITLE
when  i run this  project   hint me nullPointException

### ISSUE THREAD

**Issue by oceason** [saikrishna321/PageObjectPatternAppium#36]
Running com.appium.tests.Runner
Configuring TestNG with: TestNG652Configurator
java.lang.NullPointerException
        at com.appium.manager.DeviceAllocationManager.initializeDevices(DeviceAllocationManager.java:41)
        at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:27)

**Comment by saikrishna321** [comment]
@oceason make sure you have Platform="android" mvn clean -Dtest=Runner test

**Comment by 99heitor** [comment]
I have the same issue. I'm also running the correct command.

**Comment by saikrishna321** [comment]
@99heitor  can you pls try with below version 

```
<dependency>
    <groupId>com.github.saikrishna321</groupId>
    <artifactId>AppiumTestDistribution</artifactId>
    <version>ef50dc2</version>
</dependency>
```

**Comment by Dupleks** [comment]
I changed artifact version and now it works for me. Thanks

**Comment by oceason** [comment]
THX I'll try it
