### ISSUE TITLE
How can I use android.json file instead of writing capabilities in code

### ISSUE THREAD

**Issue by sunilpatro1985** [saikrishna321/PageObjectPatternAppium#37]
Instead of writing capabilities one by one in code before initialising the appiumdriver, can I have keep all capabilities in a json file as I see under caps/android.json and call the android.json into the code instead writing 
```
cap = new DesiredCapabilities();
cap.setCapability(CapabilityType.PLATFORM, "Android");
```

**Comment by saikrishna321** [comment]
@sunilpatro1985 you can just place all the caps as in android.json, the framework will consider and build the DesiredCapabilities for you.

**Comment by sunilpatro1985** [comment]
Thanks for responding, to more understand the framework can you please let me know which file or code block call the json file.

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/utils/DesiredCapabilityBuilder.java
