### ISSUE TITLE
Windows configuration for wiki

### ISSUE THREAD

**Issue by hemano** [saikrishna321/PageObjectPatternAppium#40]
Would you like to  update 
https://github.com/saikrishna321/AppiumTestDistribution/wiki/Configure-tests-for-TestNG 

for Windows configuration as well?
## For appium 1.6.X users (If appium installed using npm)
APPIUM_JS_PATH=C:/Users/<username>/AppData/Roaming/npm/node_modules/appium/build/lib/main.js

**Comment by saikrishna321** [comment]
@hemano i have not worked on windows tests implementation, if you have welcome for PR

**Comment by saikrishna321** [comment]
@hemano  i have updated
