### ISSUE TITLE
iOS Wordpress app not working - outdated

### ISSUE THREAD

**Issue by Akulavenkatesh** [saikrishna321/PageObjectPatternAppium#41]
When I try to login with my Wordpress credentials in iOS Wordpress app it shows an error message 
"Sorry, we can't log you in. The required "client_id" parameter is missing."

screenshot attached for you reference

<img width="363" alt="screen shot 2017-07-14 at 12 55 21 am" src="https://user-images.githubusercontent.com/1756744/28184183-f6087aa6-682f-11e7-8c2f-b61ce650a17f.png">

**Comment by saikrishna321** [comment]
@Akulavenkatesh  the iOS app has been bundled with specific login credentials ID(wpcom_app_credentials) which means it will not work your personal credentials
