### ISSUE TITLE
Error while executing mvn clean -Dtest=Runner test

### ISSUE THREAD

**Issue by sam-viz** [saikrishna321/PageObjectPatternAppium#6]
Hello,

I wanted to execute this project to get a look on an example using the AppiumTestDistribution. However, i got the following error while running '''mvn clean -Dtest=Runner test''' .
Failure to find com.relevantcodes:extentreports:jar:2.41.0-SNAPSHOT in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced 

Thank you.

**Comment by saikrishna321** [comment]
@sam-viz can you please add this to the pom.xml

```
<dependency>
    <groupId>com.relevantcodes</groupId>
    <artifactId>extentreports</artifactId>
    <version>2.41.0</version>
</dependency>
```

**Comment by sam-viz** [comment]
Many thanks !
