### ISSUE TITLE
Unable to run on iOS device

### ISSUE THREAD

**Issue by vannamaneni** [saikrishna321/PageObjectPatternAppium#8]
Hi,

Android tests went well. However, facing issues on iOS device. here is the log.

Setting iOS Desired Capabilities:
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":null,"platformVersion":"9.0","bundleId":null,"udid":"9148dc99787b0d61b4b7bae3378327e28c4af714","platformName":"iOS","deviceName":"iPhone","autoAcceptAlerts":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":null,"platformVersi...
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   app: null
[Appium]   platformVersion: '9.0'
[Appium]   bundleId: null
[Appium]   udid: '9148dc99787b0d61b4b7bae3378327e28c4af714'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone'
[Appium]   autoAcceptAlerts: true
[iOS] Error: The desired capabilities must include either an app or a bundleId for iOS
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at IosDriver.validateDesiredCaps (lib/driver.js:409:14)
    at IosDriver.callee$0$0$ (lib/basedriver/commands/session.js:14:8)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)

**Comment by saikrishna321** [comment]
@vannamaneni you need to send the below values in the config.properties

BUNDLE_ID=
IOS_APP_PATH=<absolute path to .app/.ipa>

**Comment by vannamaneni** [comment]
Thanks for quick reply.. realised my fault.
Fixed the issue by providing relevant info as mentioned above. Tried with the same wordpress.app. again into trouble .. Unable to install the same on device..

How to get wordpress.ipa with debug key ?

**Comment by priyankshah217** [comment]
Hey, how did u generate IPA, without developer  cert?

**Comment by vannamaneni** [comment]
Oh..ok, This is to run scripts on the sample wordpress app. 
Basically, I wanted to run same scripts provided in sample (on iOS device).

**Comment by priyankshah217** [comment]
This will run only on iPhone emulator, to make it work on device, your
developer need to build it using their debug certificate.

**Comment by vannamaneni** [comment]
Worked as expected with my own app on iOS.
Thanks.

**Comment by saikrishna321** [comment]
@vannamaneni Awesome 👍
